spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.datasource.hikari.connection-timeout=120000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.leak-detection-threshold=600000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.validation-timeout=10000
spring.datasource.hikari.keepalive-time=60000
