spring.config.import=optional:classpath:application-security.properties

spring.application.name=statezone

spring.datasource.url=jdbc:postgresql://localhost:5432/statzone
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
server.address=0.0.0.0
server.error.include-stacktrace=never

api-football.base-url=https://v3.football.api-sports.io
api-football.api-key=${API_FOOTBALL_KEY}


spring.flyway.enabled=true

spring.jpa.open-in-view=false

rate-limiting.enabled=false

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:1209600000}