spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.datasource.hikari.connection-timeout=120000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.leak-detection-threshold=600000
