--
-- PostgreSQL database dump
--

-- Dumped from database version 15.6 (Debian 15.6-1.pgdg120+2)
-- Dumped by pg_dump version 15.6 (Debian 15.6-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: campeonato_times; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.campeonato_times (
                                         campeonato_id bigint NOT NULL,
                                         time_id bigint NOT NULL
);

--
-- Name: campeonatos; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.campeonatos (
                                    id bigint NOT NULL,
                                    amarelos_para_suspensao integer,
                                    api_football_id bigint,
                                    atualizado_em timestamp(6) without time zone,
                                    criado_em timestamp(6) without time zone,
                                    logo_url character varying(255),
                                    nome character varying(255),
                                    pais character varying(255),
                                    temporada character varying(255),
                                    tipo_formato character varying(255),
                                    CONSTRAINT campeonatos_tipo_formato_check CHECK (((tipo_formato)::text = ANY ((ARRAY['PONTOS_CORRIDOS'::character varying, 'GRUPOS_E_MATA_MATA'::character varying, 'MATA_MATA'::character varying])::text[])))
);

ALTER TABLE public.campeonatos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campeonatos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: confrontos_eliminatorios; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.confrontos_eliminatorios (
                                                 id bigint NOT NULL,
                                                 bracket_index integer,
                                                 criado_em timestamp(6) without time zone,
                                                 gols_penaltis_a integer,
                                                 gols_penaltis_b integer,
                                                 jogo_unico boolean,
                                                 round_index integer,
                                                 seed integer,
                                                 slot_proximo integer,
                                                 status_confronto character varying(255),
                                                 fase_eliminatoria_id bigint,
                                                 partida_ida_id bigint,
                                                 partida_volta_id bigint,
                                                 proximo_confronto_id bigint,
                                                 time_a_id bigint,
                                                 time_b_id bigint,
                                                 time_classificado_id bigint,
                                                 CONSTRAINT confrontos_eliminatorios_status_confronto_check CHECK (((status_confronto)::text = ANY ((ARRAY['PENDENTE'::character varying, 'EM_ANDAMENTO'::character varying, 'AGUARDANDO_PENALTIS'::character varying, 'PENALTIS'::character varying, 'ENCERRADO'::character varying])::text[])))
);

ALTER TABLE public.confrontos_eliminatorios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.confrontos_eliminatorios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: escalacao_partida; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.escalacao_partida (
                                          id bigint NOT NULL,
                                          ativo boolean NOT NULL,
                                          atualizado_em timestamp(6) without time zone,
                                          criado_em timestamp(6) without time zone,
                                          funcao character varying(255) NOT NULL,
                                          numero_camisa integer,
                                          posicao character varying(255),
                                          jogador_id bigint NOT NULL,
                                          partida_id bigint NOT NULL,
                                          CONSTRAINT escalacao_partida_funcao_check CHECK (((funcao)::text = ANY ((ARRAY['TITULAR'::character varying, 'RESERVA'::character varying])::text[]))),
    CONSTRAINT escalacao_partida_posicao_check CHECK (((posicao)::text = ANY ((ARRAY['GOLEIRO'::character varying, 'ZAGUEIRO'::character varying, 'LATERAL_DIREITO'::character varying, 'LATERAL_ESQUERDO'::character varying, 'VOLANTE'::character varying, 'MEIO_CAMPO'::character varying, 'PONTA_DIREITA'::character varying, 'PONTA_ESQUERDA'::character varying, 'MEIA_ATACANTE'::character varying, 'CENTROAVANTE'::character varying])::text[])))
);

ALTER TABLE public.escalacao_partida ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.escalacao_partida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: estatisticas_jogador; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.estatisticas_jogador (
                                             id bigint NOT NULL,
                                             assistencias integer,
                                             cartoes_amarelos integer,
                                             cartoes_vermelhos integer,
                                             clean_sheets integer,
                                             defesas integer,
                                             faltas_cometidas integer,
                                             finalizacoes integer,
                                             gols integer,
                                             partidas_jogadas integer,
                                             penaltis_defendidos integer,
                                             penaltis_perdidos integer,
                                             jogador_id bigint
);

--
-- Name: estatisticas_jogador_campeonato; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.estatisticas_jogador_campeonato (
                                                        id bigint NOT NULL,
                                                        amarelos_desde_suspensao integer NOT NULL,
                                                        assistencias integer,
                                                        cartoes_amarelos integer,
                                                        cartoes_vermelhos integer,
                                                        clean_sheets integer,
                                                        defesas integer,
                                                        faltas_cometidas integer,
                                                        finalizacoes integer,
                                                        gols integer,
                                                        partidas_jogadas integer,
                                                        penaltis_defendidos integer,
                                                        penaltis_perdidos integer,
                                                        campeonato_id bigint NOT NULL,
                                                        jogador_id bigint NOT NULL
);

ALTER TABLE public.estatisticas_jogador_campeonato ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estatisticas_jogador_campeonato_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.estatisticas_jogador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estatisticas_jogador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: estatisticas_partida; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.estatisticas_partida (
                                             id bigint NOT NULL,
                                             cartoes_amarelos_mandante integer,
                                             cartoes_amarelos_visitante integer,
                                             cartoes_vermelhos_mandante integer,
                                             cartoes_vermelhos_visitante integer,
                                             defesas_mandante integer,
                                             defesas_visitante integer,
                                             escanteios_mandante integer,
                                             escanteios_visitante integer,
                                             faltas_mandante integer,
                                             faltas_visitante integer,
                                             finalizacoes_gol_mandante integer,
                                             finalizacoes_gol_visitante integer,
                                             finalizacoes_mandante integer,
                                             finalizacoes_visitante integer,
                                             penaltis_defendidos_mandante integer,
                                             penaltis_defendidos_visitante integer,
                                             posse_bola_mandante integer,
                                             posse_bola_visitante integer,
                                             substituicoes_mandante integer,
                                             substituicoes_visitante integer,
                                             partida_id bigint
);

ALTER TABLE public.estatisticas_partida ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estatisticas_partida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: eventos_partida; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.eventos_partida (
                                        id bigint NOT NULL,
                                        anulado boolean NOT NULL,
                                        criado_em timestamp(6) without time zone,
                                        descricao character varying(255),
                                        minuto integer,
                                        minuto_extra integer,
                                        tipo_evento character varying(255),
                                        evento_relacionado_id bigint,
                                        jogador_id bigint,
                                        jogador_secundario_id bigint,
                                        partida_id bigint,
                                        time_id bigint,
                                        CONSTRAINT eventos_partida_tipo_evento_check CHECK (((tipo_evento)::text = ANY ((ARRAY['GOL'::character varying, 'GOL_CONTRA'::character varying, 'PENALTI_GOL'::character varying, 'PENALTI_PERDIDO'::character varying, 'FINALIZACAO'::character varying, 'FINALIZACAO_NO_GOL'::character varying, 'DEFESA'::character varying, 'PENALTI_DEFENDIDO'::character varying, 'FALTA'::character varying, 'CARTAO_AMARELO'::character varying, 'CARTAO_VERMELHO'::character varying, 'IMPEDIMENTO'::character varying, 'ESCANTEIO'::character varying, 'VAR_GOL_CONFIRMADO'::character varying, 'VAR_GOL_ANULADO'::character varying, 'SUBSTITUICAO'::character varying, 'INICIO_PRIMEIRO_TEMPO'::character varying, 'FIM_PRIMEIRO_TEMPO'::character varying, 'INICIO_SEGUNDO_TEMPO'::character varying, 'FIM_PARTIDA'::character varying])::text[])))
);

ALTER TABLE public.eventos_partida ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_partida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: fases_eliminatorias; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.fases_eliminatorias (
                                            id bigint NOT NULL,
                                            criado_em timestamp(6) without time zone,
                                            fase character varying(255) NOT NULL,
                                            jogo_unico boolean NOT NULL,
                                            campeonato_id bigint NOT NULL,
                                            CONSTRAINT fases_eliminatorias_fase_check CHECK (((fase)::text = ANY ((ARRAY['OITAVAS'::character varying, 'QUARTAS'::character varying, 'SEMIFINAL'::character varying, 'TERCEIRO_LUGAR'::character varying, 'FINAL'::character varying])::text[])))
);

ALTER TABLE public.fases_eliminatorias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fases_eliminatorias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: grupo_times; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.grupo_times (
                                    grupo_id bigint NOT NULL,
                                    time_id bigint NOT NULL
);

--
-- Name: grupos; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.grupos (
                               id bigint NOT NULL,
                               criado_em timestamp(6) without time zone,
                               nome character varying(255) NOT NULL,
                               campeonato_id bigint NOT NULL
);

ALTER TABLE public.grupos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grupos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: jogadores; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.jogadores (
                                  id bigint NOT NULL,
                                  altura numeric(38,2),
                                  api_football_id bigint,
                                  atualizado_em timestamp(6) without time zone,
                                  criado_em timestamp(6) without time zone,
                                  data_nascimento date,
                                  foto_url character varying(255),
                                  nacionalidade character varying(255),
                                  nome character varying(255),
                                  numero_camisa integer,
                                  pe_forte character varying(255),
                                  peso numeric(38,2),
                                  posicao character varying(255),
                                  valor_mercado numeric(38,2),
                                  time_id bigint,
                                  CONSTRAINT jogadores_pe_forte_check CHECK (((pe_forte)::text = ANY ((ARRAY['DIREITO'::character varying, 'ESQUERDO'::character varying, 'AMBIDESTRO'::character varying])::text[]))),
    CONSTRAINT jogadores_posicao_check CHECK (((posicao)::text = ANY ((ARRAY['GOLEIRO'::character varying, 'ZAGUEIRO'::character varying, 'LATERAL_DIREITO'::character varying, 'LATERAL_ESQUERDO'::character varying, 'VOLANTE'::character varying, 'MEIO_CAMPO'::character varying, 'PONTA_DIREITA'::character varying, 'PONTA_ESQUERDA'::character varying, 'MEIA_ATACANTE'::character varying, 'CENTROAVANTE'::character varying])::text[])))
);

ALTER TABLE public.jogadores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jogadores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: partidas; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.partidas (
                                 id bigint NOT NULL,
                                 api_football_id bigint,
                                 arbitro character varying(255),
                                 atualizado_em timestamp(6) without time zone,
                                 criado_em timestamp(6) without time zone,
                                 data_partida timestamp(6) without time zone,
                                 estadio character varying(255),
                                 gols_mandante integer NOT NULL,
                                 gols_penaltis_mandante integer,
                                 gols_penaltis_visitante integer,
                                 gols_visitante integer NOT NULL,
                                 rodada integer,
                                 status character varying(255),
                                 campeonato_id bigint,
                                 fase_eliminatoria_id bigint,
                                 grupo_id bigint,
                                 time_mandante_id bigint,
                                 time_visitante_id bigint,
                                 CONSTRAINT partidas_status_check CHECK (((status)::text = ANY ((ARRAY['AGENDADA'::character varying, 'AO_VIVO'::character varying, 'ENCERRADA'::character varying, 'ADIADA'::character varying, 'CANCELADA'::character varying, 'INTERVALO'::character varying, 'WO_MANDANTE'::character varying, 'PENALTIS'::character varying, 'WO_VISITANTE'::character varying])::text[])))
);

ALTER TABLE public.partidas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partidas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: processamento_confronto_pendente; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.processamento_confronto_pendente (
                                                         id bigint NOT NULL,
                                                         criado_em timestamp(6) without time zone,
                                                         partida_id bigint,
                                                         resolvido boolean NOT NULL,
                                                         tentativas integer NOT NULL,
                                                         ultimo_erro character varying(255)
);

ALTER TABLE public.processamento_confronto_pendente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.processamento_confronto_pendente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: suspensoes; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.suspensoes (
                                   id bigint NOT NULL,
                                   criado_em timestamp(6) without time zone,
                                   motivo character varying(255) NOT NULL,
                                   rodada_suspensao integer,
                                   campeonato_id bigint NOT NULL,
                                   jogador_id bigint NOT NULL,
                                   partida_alvo_id bigint,
                                   CONSTRAINT suspensoes_motivo_check CHECK (((motivo)::text = ANY ((ARRAY['ACUMULO_AMARELOS'::character varying, 'CARTAO_VERMELHO'::character varying])::text[])))
);

ALTER TABLE public.suspensoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suspensoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: times; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.times (
                              id bigint NOT NULL,
                              api_football_id bigint,
                              atualizado_em timestamp(6) without time zone,
                              cidade character varying(255),
                              criado_em timestamp(6) without time zone,
                              escudo_url character varying(255),
                              estadio character varying(255),
                              fundado_em date,
                              nome character varying(255),
                              pais character varying(255),
                              seed integer,
                              sigla character varying(255),
                              tecnico character varying(255)
);

ALTER TABLE public.times ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.times_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.usuarios (
                                 id bigint NOT NULL,
                                 email character varying(255) NOT NULL,
                                 role character varying(255),
                                 senha character varying(255) NOT NULL,
                                 CONSTRAINT usuarios_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Primary keys
--

ALTER TABLE ONLY public.campeonatos
    ADD CONSTRAINT campeonatos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT confrontos_eliminatorios_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.escalacao_partida
    ADD CONSTRAINT escalacao_partida_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.estatisticas_jogador_campeonato
    ADD CONSTRAINT estatisticas_jogador_campeonato_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.estatisticas_jogador
    ADD CONSTRAINT estatisticas_jogador_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.estatisticas_partida
    ADD CONSTRAINT estatisticas_partida_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.eventos_partida
    ADD CONSTRAINT eventos_partida_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.fases_eliminatorias
    ADD CONSTRAINT fases_eliminatorias_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.grupo_times
    ADD CONSTRAINT grupo_times_pkey PRIMARY KEY (grupo_id, time_id);

ALTER TABLE ONLY public.grupos
    ADD CONSTRAINT grupos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.jogadores
    ADD CONSTRAINT jogadores_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT partidas_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.processamento_confronto_pendente
    ADD CONSTRAINT processamento_confronto_pendente_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.suspensoes
    ADD CONSTRAINT suspensoes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.times
    ADD CONSTRAINT times_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.campeonato_times
    ADD CONSTRAINT campeonato_times_pkey PRIMARY KEY (campeonato_id, time_id);

--
-- Unique constraints
--

ALTER TABLE ONLY public.estatisticas_jogador
    ADD CONSTRAINT uk3n0ed6jbwb8xhuqrmtrg3d8cb UNIQUE (jogador_id);

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT uk4sv5v1pthj5k0olsx4kdl7945 UNIQUE (partida_volta_id);

ALTER TABLE ONLY public.jogadores
    ADD CONSTRAINT uk5cw7afvrsoxlld9ps07rgtrne UNIQUE (api_football_id);

ALTER TABLE ONLY public.escalacao_partida
    ADD CONSTRAINT uk65485596irhqjet2by9qrh6yd UNIQUE (partida_id, jogador_id);

ALTER TABLE ONLY public.times
    ADD CONSTRAINT uk73xjli5hh7mq76pqg4myqedm7 UNIQUE (api_football_id);

ALTER TABLE ONLY public.grupos
    ADD CONSTRAINT uk796lvrdease2hky60wviuqb4j UNIQUE (campeonato_id, nome);

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT ukenqbgtrdax9cw53hecljg3ub2 UNIQUE (partida_ida_id);

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT ukhg3lutywqfcxgh14n0fntckca UNIQUE (api_football_id);

ALTER TABLE ONLY public.estatisticas_partida
    ADD CONSTRAINT ukicc0scoc6xjd5hj8paa6ouqa6 UNIQUE (partida_id);

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);

ALTER TABLE ONLY public.campeonatos
    ADD CONSTRAINT ukt5c094v5c9p60elfuaeem1jti UNIQUE (api_football_id);

ALTER TABLE ONLY public.estatisticas_jogador_campeonato
    ADD CONSTRAINT uktiwyff467l4uxc7eocchvea5j UNIQUE (jogador_id, campeonato_id);

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);

--
-- Foreign keys
--

ALTER TABLE ONLY public.eventos_partida
    ADD CONSTRAINT fk1da7qframdyj0190wo6ntflk FOREIGN KEY (jogador_id) REFERENCES public.jogadores(id);

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fk2hmwfapy52y6w85o0vwgs9qye FOREIGN KEY (time_b_id) REFERENCES public.times(id);

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT fk5cwpdvqqsf0ffk12bmbinf9rg FOREIGN KEY (grupo_id) REFERENCES public.grupos(id);

ALTER TABLE ONLY public.estatisticas_jogador_campeonato
    ADD CONSTRAINT fk63shvhfgvg09cjunm72pgrbo5 FOREIGN KEY (campeonato_id) REFERENCES public.campeonatos(id);

ALTER TABLE ONLY public.eventos_partida
    ADD CONSTRAINT fk6toxjj0fahbjv7tb3uuj6yyrt FOREIGN KEY (evento_relacionado_id) REFERENCES public.eventos_partida(id);

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fk6yykmx06cnqmngfq10t889w9c FOREIGN KEY (time_a_id) REFERENCES public.times(id);

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT fk7tkc3n5dhx25x14dcd2jc6ffb FOREIGN KEY (time_visitante_id) REFERENCES public.times(id);

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT fk9bnkub8ktuqlo80a6ykleed45 FOREIGN KEY (time_mandante_id) REFERENCES public.times(id);

ALTER TABLE ONLY public.estatisticas_partida
    ADD CONSTRAINT fk9tuy0qu4ph6pcrb5kkje9aw77 FOREIGN KEY (partida_id) REFERENCES public.partidas(id);

ALTER TABLE ONLY public.fases_eliminatorias
    ADD CONSTRAINT fkabytb9qtow6jrarjk0wa8l3io FOREIGN KEY (campeonato_id) REFERENCES public.campeonatos(id);

ALTER TABLE ONLY public.eventos_partida
    ADD CONSTRAINT fkag92pytennqxeir55twbhkoen FOREIGN KEY (time_id) REFERENCES public.times(id);

ALTER TABLE ONLY public.suspensoes
    ADD CONSTRAINT fkaim4k4g47evuqf85he414l0qr FOREIGN KEY (campeonato_id) REFERENCES public.campeonatos(id);

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fkast3jx3jyshfrj8f8udbgtunn FOREIGN KEY (fase_eliminatoria_id) REFERENCES public.fases_eliminatorias(id);

ALTER TABLE ONLY public.suspensoes
    ADD CONSTRAINT fkba299nugwdcws8ug5065a24hn FOREIGN KEY (partida_alvo_id) REFERENCES public.partidas(id);

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fkc0bjsnhibfxoc54930et2p2rd FOREIGN KEY (partida_ida_id) REFERENCES public.partidas(id);

ALTER TABLE ONLY public.suspensoes
    ADD CONSTRAINT fkdtsji0k6v7730yyy9x3tef9i9 FOREIGN KEY (jogador_id) REFERENCES public.jogadores(id);

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT fkdwjii304ggmk4ktfl8oh2e7rq FOREIGN KEY (fase_eliminatoria_id) REFERENCES public.fases_eliminatorias(id);

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fkeisko2aofhc8yuteebt1knarb FOREIGN KEY (partida_volta_id) REFERENCES public.partidas(id);

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fkgmc7gy4i6wqhpap1q3lcwnqhe FOREIGN KEY (time_classificado_id) REFERENCES public.times(id);

ALTER TABLE ONLY public.eventos_partida
    ADD CONSTRAINT fkguvwalm0cc4yu7jvy7w1efy73 FOREIGN KEY (jogador_secundario_id) REFERENCES public.jogadores(id);

ALTER TABLE ONLY public.escalacao_partida
    ADD CONSTRAINT fkhw2womnp2ytckrgxgcmcainup FOREIGN KEY (partida_id) REFERENCES public.partidas(id);

ALTER TABLE ONLY public.jogadores
    ADD CONSTRAINT fkhxsr8cown495046kok6v10is FOREIGN KEY (time_id) REFERENCES public.times(id);

ALTER TABLE ONLY public.campeonato_times
    ADD CONSTRAINT fkljk9uxd555il3y3sxh1xndfoe FOREIGN KEY (campeonato_id) REFERENCES public.campeonatos(id);

ALTER TABLE ONLY public.escalacao_partida
    ADD CONSTRAINT fknhdi12yixa0ynsafvpapmkhrp FOREIGN KEY (jogador_id) REFERENCES public.jogadores(id);

ALTER TABLE ONLY public.estatisticas_jogador
    ADD CONSTRAINT fko5457s5lmli1dwfe4uohks12v FOREIGN KEY (jogador_id) REFERENCES public.jogadores(id);

ALTER TABLE ONLY public.campeonato_times
    ADD CONSTRAINT fkompdnlc2fyjiujv0yr2wo1gvh FOREIGN KEY (time_id) REFERENCES public.times(id);

ALTER TABLE ONLY public.estatisticas_jogador_campeonato
    ADD CONSTRAINT fkovosqelveqpw6t6n358dbpq7y FOREIGN KEY (jogador_id) REFERENCES public.jogadores(id);

ALTER TABLE ONLY public.grupos
    ADD CONSTRAINT fkp2b1e5roc2reqtdaihhe0pw6s FOREIGN KEY (campeonato_id) REFERENCES public.campeonatos(id);

ALTER TABLE ONLY public.grupo_times
    ADD CONSTRAINT fkqhj7scexf6335c2bxug95ixh7 FOREIGN KEY (grupo_id) REFERENCES public.grupos(id);

ALTER TABLE ONLY public.eventos_partida
    ADD CONSTRAINT fkqyd97ou5ne6rtfv4ecii99umy FOREIGN KEY (partida_id) REFERENCES public.partidas(id);

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT fkr0y6qpiuxfir2ld48mrpvrw7x FOREIGN KEY (campeonato_id) REFERENCES public.campeonatos(id);

ALTER TABLE ONLY public.grupo_times
    ADD CONSTRAINT fksri9223x40fk9in88n9oxsow8 FOREIGN KEY (time_id) REFERENCES public.times(id);

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fktli36q3oy0aqb7x2v3i3qd8qo FOREIGN KEY (proximo_confronto_id) REFERENCES public.confrontos_eliminatorios(id);

--
-- PostgreSQL database dump complete
--