import { lazy } from 'react';

export const LoginPage = lazy(() => import('./LoginPage'));
export const RegisterPage = lazy(() => import('./RegisterPage'));
export const DashboardPage = lazy(() => import('./DashboardPage'));
export const CampeonatosPage = lazy(() => import('./CampeonatosPage'));
export const TimesPage = lazy(() => import('./TimesPage'));
export const TimeDetalhePage = lazy(() => import('./TimeDetalhePage'));
export const JogadoresPage = lazy(() => import('./JogadoresPage'));
export const PartidasPage = lazy(() => import('./PartidasPage'));
export const PartidaDetalhePage = lazy(() => import('./PartidaDetalhePage'));
export const EstatisticasPage = lazy(() => import('./EstatisticasPage'));
export const FasesPage = lazy(() => import('./FasesPage'));
export const ImportacaoPage = lazy(() => import('./ImportacaoPage'));
export const PublicHomePage = lazy(() => import('./PublicHomePage'));
export const PublicCampeonatosPage = lazy(() => import('./PublicCampeonatosPage'));
export const PublicTimesPage = lazy(() => import('./PublicTimesPage'));
export const CampeonatoDetalhePage = lazy(() => import('./CampeonatoDetalhePage'));
export const JogadorDetalhePage = lazy(() => import('./JogadorDetalhePage'));
export const NotFoundPage = lazy(() => import('./NotFoundPage'));
