export const STATUS_PARTIDA = {
  AGENDADA: 'AGENDADA' as const,
  AO_VIVO: 'AO_VIVO' as const,
  INTERVALO: 'INTERVALO' as const,
  PENALTIS: 'PENALTIS' as const,
  ENCERRADA: 'ENCERRADA' as const,
  ADIADA: 'ADIADA' as const,
  CANCELADA: 'CANCELADA' as const,
  WO_MANDANTE: 'WO_MANDANTE' as const,
  WO_VISITANTE: 'WO_VISITANTE' as const,
} as const;

export const STATUS_AO_VIVO = [STATUS_PARTIDA.AO_VIVO, STATUS_PARTIDA.PENALTIS, STATUS_PARTIDA.INTERVALO] as const;
export const STATUS_ENCERRADA = [STATUS_PARTIDA.ENCERRADA, STATUS_PARTIDA.WO_MANDANTE, STATUS_PARTIDA.WO_VISITANTE] as const;
