--
-- PostgreSQL database dump
--

\restrict AUCGz7AfKK5sqfPAz5VCb3hqq23GnDfx6JgCQaQFmoFNPaNqQ1VgDGQlbcDSOx2

-- Dumped from database version 15.6 (Debian 15.6-1.pgdg120+2)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: campeonato_times; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campeonato_times (
    campeonato_id bigint NOT NULL,
    time_id bigint NOT NULL
);


--
-- Name: campeonatos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campeonatos (
    amarelos_para_suspensao integer,
    api_football_id bigint,
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone,
    id bigint NOT NULL,
    logo_url character varying(255),
    nome character varying(255),
    pais character varying(255),
    temporada character varying(255),
    tipo_formato character varying(255),
    CONSTRAINT campeonatos_tipo_formato_check CHECK (((tipo_formato)::text = ANY ((ARRAY['PONTOS_CORRIDOS'::character varying, 'GRUPOS_E_MATA_MATA'::character varying, 'MATA_MATA'::character varying])::text[])))
);


--
-- Name: campeonatos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.campeonatos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campeonatos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: confrontos_eliminatorios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.confrontos_eliminatorios (
    bracket_index integer,
    gols_penaltis_a integer,
    gols_penaltis_b integer,
    jogo_unico boolean,
    round_index integer,
    seed integer,
    slot_proximo integer,
    criado_em timestamp(6) without time zone,
    fase_eliminatoria_id bigint,
    id bigint NOT NULL,
    partida_ida_id bigint,
    partida_volta_id bigint,
    proximo_confronto_id bigint,
    time_a_id bigint,
    time_b_id bigint,
    time_classificado_id bigint,
    status_confronto character varying(255),
    CONSTRAINT confrontos_eliminatorios_status_confronto_check CHECK (((status_confronto)::text = ANY ((ARRAY['PENDENTE'::character varying, 'EM_ANDAMENTO'::character varying, 'AGUARDANDO_PENALTIS'::character varying, 'PENALTIS'::character varying, 'ENCERRADO'::character varying])::text[])))
);


--
-- Name: confrontos_eliminatorios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.confrontos_eliminatorios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.confrontos_eliminatorios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: escalacao_partida; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.escalacao_partida (
    ativo boolean NOT NULL,
    numero_camisa integer,
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone,
    id bigint NOT NULL,
    jogador_id bigint NOT NULL,
    partida_id bigint NOT NULL,
    funcao character varying(255) NOT NULL,
    posicao character varying(255),
    CONSTRAINT escalacao_partida_funcao_check CHECK (((funcao)::text = ANY ((ARRAY['TITULAR'::character varying, 'RESERVA'::character varying])::text[]))),
    CONSTRAINT escalacao_partida_posicao_check CHECK (((posicao)::text = ANY ((ARRAY['GOLEIRO'::character varying, 'ZAGUEIRO'::character varying, 'LATERAL_DIREITO'::character varying, 'LATERAL_ESQUERDO'::character varying, 'VOLANTE'::character varying, 'MEIO_CAMPO'::character varying, 'PONTA_DIREITA'::character varying, 'PONTA_ESQUERDA'::character varying, 'MEIA_ATACANTE'::character varying, 'CENTROAVANTE'::character varying])::text[])))
);


--
-- Name: escalacao_partida_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.escalacao_partida ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.escalacao_partida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estatisticas_jogador; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estatisticas_jogador (
    assistencias integer,
    cartoes_amarelos integer,
    cartoes_vermelhos integer,
    clean_sheets integer,
    defesas integer,
    faltas_cometidas integer,
    finalizacoes integer,
    gols integer,
    partidas_jogadas integer,
    penaltis_defendidos integer,
    penaltis_perdidos integer,
    id bigint NOT NULL,
    jogador_id bigint
);


--
-- Name: estatisticas_jogador_campeonato; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estatisticas_jogador_campeonato (
    amarelos_desde_suspensao integer NOT NULL,
    assistencias integer,
    cartoes_amarelos integer,
    cartoes_vermelhos integer,
    clean_sheets integer,
    defesas integer,
    faltas_cometidas integer,
    finalizacoes integer,
    gols integer,
    partidas_jogadas integer,
    penaltis_defendidos integer,
    penaltis_perdidos integer,
    campeonato_id bigint NOT NULL,
    id bigint NOT NULL,
    jogador_id bigint NOT NULL
);


--
-- Name: estatisticas_jogador_campeonato_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estatisticas_jogador_campeonato ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estatisticas_jogador_campeonato_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estatisticas_jogador_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estatisticas_jogador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estatisticas_jogador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estatisticas_partida; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estatisticas_partida (
    cartoes_amarelos_mandante integer,
    cartoes_amarelos_visitante integer,
    cartoes_vermelhos_mandante integer,
    cartoes_vermelhos_visitante integer,
    defesas_mandante integer,
    defesas_visitante integer,
    escanteios_mandante integer,
    escanteios_visitante integer,
    faltas_mandante integer,
    faltas_visitante integer,
    finalizacoes_gol_mandante integer,
    finalizacoes_gol_visitante integer,
    finalizacoes_mandante integer,
    finalizacoes_visitante integer,
    penaltis_defendidos_mandante integer,
    penaltis_defendidos_visitante integer,
    posse_bola_mandante integer,
    posse_bola_visitante integer,
    substituicoes_mandante integer,
    substituicoes_visitante integer,
    id bigint NOT NULL,
    partida_id bigint
);


--
-- Name: estatisticas_partida_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estatisticas_partida ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estatisticas_partida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: eventos_partida; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eventos_partida (
    anulado boolean NOT NULL,
    minuto integer,
    minuto_extra integer,
    criado_em timestamp(6) without time zone,
    evento_relacionado_id bigint,
    id bigint NOT NULL,
    jogador_id bigint,
    jogador_secundario_id bigint,
    partida_id bigint,
    time_id bigint,
    descricao character varying(255),
    tipo_evento character varying(255),
    CONSTRAINT eventos_partida_tipo_evento_check CHECK (((tipo_evento)::text = ANY ((ARRAY['GOL'::character varying, 'GOL_CONTRA'::character varying, 'PENALTI_GOL'::character varying, 'PENALTI_PERDIDO'::character varying, 'FINALIZACAO'::character varying, 'FINALIZACAO_NO_GOL'::character varying, 'DEFESA'::character varying, 'PENALTI_DEFENDIDO'::character varying, 'FALTA'::character varying, 'CARTAO_AMARELO'::character varying, 'CARTAO_VERMELHO'::character varying, 'IMPEDIMENTO'::character varying, 'ESCANTEIO'::character varying, 'VAR_GOL_CONFIRMADO'::character varying, 'VAR_GOL_ANULADO'::character varying, 'SUBSTITUICAO'::character varying, 'INICIO_PRIMEIRO_TEMPO'::character varying, 'FIM_PRIMEIRO_TEMPO'::character varying, 'INICIO_SEGUNDO_TEMPO'::character varying, 'FIM_PARTIDA'::character varying])::text[])))
);


--
-- Name: eventos_partida_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.eventos_partida ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_partida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fases_eliminatorias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fases_eliminatorias (
    jogo_unico boolean NOT NULL,
    campeonato_id bigint NOT NULL,
    criado_em timestamp(6) without time zone,
    id bigint NOT NULL,
    fase character varying(255) NOT NULL,
    CONSTRAINT fases_eliminatorias_fase_check CHECK (((fase)::text = ANY ((ARRAY['OITAVAS'::character varying, 'QUARTAS'::character varying, 'SEMIFINAL'::character varying, 'TERCEIRO_LUGAR'::character varying, 'FINAL'::character varying])::text[])))
);


--
-- Name: fases_eliminatorias_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fases_eliminatorias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fases_eliminatorias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: grupo_times; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grupo_times (
    grupo_id bigint NOT NULL,
    time_id bigint NOT NULL
);


--
-- Name: grupos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grupos (
    campeonato_id bigint NOT NULL,
    criado_em timestamp(6) without time zone,
    id bigint NOT NULL,
    nome character varying(255) NOT NULL
);


--
-- Name: grupos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grupos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grupos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jogadores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jogadores (
    altura numeric(38,2),
    data_nascimento date,
    numero_camisa integer,
    peso numeric(38,2),
    valor_mercado numeric(38,2),
    api_football_id bigint,
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone,
    id bigint NOT NULL,
    time_id bigint,
    foto_url character varying(255),
    nacionalidade character varying(255),
    nome character varying(255),
    pe_forte character varying(255),
    posicao character varying(255),
    CONSTRAINT jogadores_pe_forte_check CHECK (((pe_forte)::text = ANY ((ARRAY['DIREITO'::character varying, 'ESQUERDO'::character varying, 'AMBIDESTRO'::character varying])::text[]))),
    CONSTRAINT jogadores_posicao_check CHECK (((posicao)::text = ANY ((ARRAY['GOLEIRO'::character varying, 'ZAGUEIRO'::character varying, 'LATERAL_DIREITO'::character varying, 'LATERAL_ESQUERDO'::character varying, 'VOLANTE'::character varying, 'MEIO_CAMPO'::character varying, 'PONTA_DIREITA'::character varying, 'PONTA_ESQUERDA'::character varying, 'MEIA_ATACANTE'::character varying, 'CENTROAVANTE'::character varying])::text[])))
);


--
-- Name: jogadores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.jogadores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jogadores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partidas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partidas (
    gols_mandante integer NOT NULL,
    gols_penaltis_mandante integer,
    gols_penaltis_visitante integer,
    gols_visitante integer NOT NULL,
    rodada integer,
    api_football_id bigint,
    atualizado_em timestamp(6) without time zone,
    campeonato_id bigint,
    criado_em timestamp(6) without time zone,
    data_partida timestamp(6) without time zone,
    fase_eliminatoria_id bigint,
    grupo_id bigint,
    id bigint NOT NULL,
    time_mandante_id bigint,
    time_visitante_id bigint,
    arbitro character varying(255),
    estadio character varying(255),
    status character varying(255),
    CONSTRAINT partidas_status_check CHECK (((status)::text = ANY ((ARRAY['AGENDADA'::character varying, 'AO_VIVO'::character varying, 'ENCERRADA'::character varying, 'ADIADA'::character varying, 'CANCELADA'::character varying, 'INTERVALO'::character varying, 'WO_MANDANTE'::character varying, 'PENALTIS'::character varying, 'WO_VISITANTE'::character varying])::text[])))
);


--
-- Name: partidas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.partidas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partidas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: processamento_confronto_pendente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.processamento_confronto_pendente (
    resolvido boolean NOT NULL,
    tentativas integer NOT NULL,
    criado_em timestamp(6) without time zone,
    id bigint NOT NULL,
    partida_id bigint,
    ultimo_erro character varying(255)
);


--
-- Name: processamento_confronto_pendente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.processamento_confronto_pendente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.processamento_confronto_pendente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suspensoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suspensoes (
    rodada_suspensao integer,
    campeonato_id bigint NOT NULL,
    criado_em timestamp(6) without time zone,
    id bigint NOT NULL,
    jogador_id bigint NOT NULL,
    partida_alvo_id bigint,
    motivo character varying(255) NOT NULL,
    CONSTRAINT suspensoes_motivo_check CHECK (((motivo)::text = ANY ((ARRAY['ACUMULO_AMARELOS'::character varying, 'CARTAO_VERMELHO'::character varying])::text[])))
);


--
-- Name: suspensoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suspensoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suspensoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: times; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.times (
    fundado_em date,
    seed integer,
    api_football_id bigint,
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone,
    id bigint NOT NULL,
    cidade character varying(255),
    escudo_url character varying(255),
    estadio character varying(255),
    nome character varying(255),
    pais character varying(255),
    sigla character varying(255),
    tecnico character varying(255)
);


--
-- Name: times_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.times ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.times_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    role character varying(255),
    senha character varying(255) NOT NULL,
    CONSTRAINT usuarios_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campeonatos campeonatos_api_football_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campeonatos
    ADD CONSTRAINT campeonatos_api_football_id_key UNIQUE (api_football_id);


--
-- Name: campeonatos campeonatos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campeonatos
    ADD CONSTRAINT campeonatos_pkey PRIMARY KEY (id);


--
-- Name: confrontos_eliminatorios confrontos_eliminatorios_partida_ida_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT confrontos_eliminatorios_partida_ida_id_key UNIQUE (partida_ida_id);


--
-- Name: confrontos_eliminatorios confrontos_eliminatorios_partida_volta_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT confrontos_eliminatorios_partida_volta_id_key UNIQUE (partida_volta_id);


--
-- Name: confrontos_eliminatorios confrontos_eliminatorios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT confrontos_eliminatorios_pkey PRIMARY KEY (id);


--
-- Name: escalacao_partida escalacao_partida_partida_id_jogador_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escalacao_partida
    ADD CONSTRAINT escalacao_partida_partida_id_jogador_id_key UNIQUE (partida_id, jogador_id);


--
-- Name: escalacao_partida escalacao_partida_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escalacao_partida
    ADD CONSTRAINT escalacao_partida_pkey PRIMARY KEY (id);


--
-- Name: estatisticas_jogador_campeonato estatisticas_jogador_campeonato_jogador_id_campeonato_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estatisticas_jogador_campeonato
    ADD CONSTRAINT estatisticas_jogador_campeonato_jogador_id_campeonato_id_key UNIQUE (jogador_id, campeonato_id);


--
-- Name: estatisticas_jogador_campeonato estatisticas_jogador_campeonato_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estatisticas_jogador_campeonato
    ADD CONSTRAINT estatisticas_jogador_campeonato_pkey PRIMARY KEY (id);


--
-- Name: estatisticas_jogador estatisticas_jogador_jogador_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estatisticas_jogador
    ADD CONSTRAINT estatisticas_jogador_jogador_id_key UNIQUE (jogador_id);


--
-- Name: estatisticas_jogador estatisticas_jogador_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estatisticas_jogador
    ADD CONSTRAINT estatisticas_jogador_pkey PRIMARY KEY (id);


--
-- Name: estatisticas_partida estatisticas_partida_partida_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estatisticas_partida
    ADD CONSTRAINT estatisticas_partida_partida_id_key UNIQUE (partida_id);


--
-- Name: estatisticas_partida estatisticas_partida_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estatisticas_partida
    ADD CONSTRAINT estatisticas_partida_pkey PRIMARY KEY (id);


--
-- Name: eventos_partida eventos_partida_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_partida
    ADD CONSTRAINT eventos_partida_pkey PRIMARY KEY (id);


--
-- Name: fases_eliminatorias fases_eliminatorias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fases_eliminatorias
    ADD CONSTRAINT fases_eliminatorias_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: grupos grupos_campeonato_id_nome_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos
    ADD CONSTRAINT grupos_campeonato_id_nome_key UNIQUE (campeonato_id, nome);


--
-- Name: grupos grupos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos
    ADD CONSTRAINT grupos_pkey PRIMARY KEY (id);


--
-- Name: jogadores jogadores_api_football_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jogadores
    ADD CONSTRAINT jogadores_api_football_id_key UNIQUE (api_football_id);


--
-- Name: jogadores jogadores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jogadores
    ADD CONSTRAINT jogadores_pkey PRIMARY KEY (id);


--
-- Name: partidas partidas_api_football_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT partidas_api_football_id_key UNIQUE (api_football_id);


--
-- Name: partidas partidas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT partidas_pkey PRIMARY KEY (id);


--
-- Name: processamento_confronto_pendente processamento_confronto_pendente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processamento_confronto_pendente
    ADD CONSTRAINT processamento_confronto_pendente_pkey PRIMARY KEY (id);


--
-- Name: suspensoes suspensoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suspensoes
    ADD CONSTRAINT suspensoes_pkey PRIMARY KEY (id);


--
-- Name: times times_api_football_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.times
    ADD CONSTRAINT times_api_football_id_key UNIQUE (api_football_id);


--
-- Name: times times_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.times
    ADD CONSTRAINT times_pkey PRIMARY KEY (id);


--
-- Name: usuarios usuarios_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: eventos_partida fk1da7qframdyj0190wo6ntflk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_partida
    ADD CONSTRAINT fk1da7qframdyj0190wo6ntflk FOREIGN KEY (jogador_id) REFERENCES public.jogadores(id);


--
-- Name: confrontos_eliminatorios fk2hmwfapy52y6w85o0vwgs9qye; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fk2hmwfapy52y6w85o0vwgs9qye FOREIGN KEY (time_b_id) REFERENCES public.times(id);


--
-- Name: partidas fk5cwpdvqqsf0ffk12bmbinf9rg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT fk5cwpdvqqsf0ffk12bmbinf9rg FOREIGN KEY (grupo_id) REFERENCES public.grupos(id);


--
-- Name: estatisticas_jogador_campeonato fk63shvhfgvg09cjunm72pgrbo5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estatisticas_jogador_campeonato
    ADD CONSTRAINT fk63shvhfgvg09cjunm72pgrbo5 FOREIGN KEY (campeonato_id) REFERENCES public.campeonatos(id);


--
-- Name: eventos_partida fk6toxjj0fahbjv7tb3uuj6yyrt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_partida
    ADD CONSTRAINT fk6toxjj0fahbjv7tb3uuj6yyrt FOREIGN KEY (evento_relacionado_id) REFERENCES public.eventos_partida(id);


--
-- Name: confrontos_eliminatorios fk6yykmx06cnqmngfq10t889w9c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fk6yykmx06cnqmngfq10t889w9c FOREIGN KEY (time_a_id) REFERENCES public.times(id);


--
-- Name: partidas fk7tkc3n5dhx25x14dcd2jc6ffb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT fk7tkc3n5dhx25x14dcd2jc6ffb FOREIGN KEY (time_visitante_id) REFERENCES public.times(id);


--
-- Name: partidas fk9bnkub8ktuqlo80a6ykleed45; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT fk9bnkub8ktuqlo80a6ykleed45 FOREIGN KEY (time_mandante_id) REFERENCES public.times(id);


--
-- Name: estatisticas_partida fk9tuy0qu4ph6pcrb5kkje9aw77; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estatisticas_partida
    ADD CONSTRAINT fk9tuy0qu4ph6pcrb5kkje9aw77 FOREIGN KEY (partida_id) REFERENCES public.partidas(id);


--
-- Name: fases_eliminatorias fkabytb9qtow6jrarjk0wa8l3io; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fases_eliminatorias
    ADD CONSTRAINT fkabytb9qtow6jrarjk0wa8l3io FOREIGN KEY (campeonato_id) REFERENCES public.campeonatos(id);


--
-- Name: eventos_partida fkag92pytennqxeir55twbhkoen; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_partida
    ADD CONSTRAINT fkag92pytennqxeir55twbhkoen FOREIGN KEY (time_id) REFERENCES public.times(id);


--
-- Name: suspensoes fkaim4k4g47evuqf85he414l0qr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suspensoes
    ADD CONSTRAINT fkaim4k4g47evuqf85he414l0qr FOREIGN KEY (campeonato_id) REFERENCES public.campeonatos(id);


--
-- Name: confrontos_eliminatorios fkast3jx3jyshfrj8f8udbgtunn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fkast3jx3jyshfrj8f8udbgtunn FOREIGN KEY (fase_eliminatoria_id) REFERENCES public.fases_eliminatorias(id);


--
-- Name: suspensoes fkba299nugwdcws8ug5065a24hn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suspensoes
    ADD CONSTRAINT fkba299nugwdcws8ug5065a24hn FOREIGN KEY (partida_alvo_id) REFERENCES public.partidas(id);


--
-- Name: confrontos_eliminatorios fkc0bjsnhibfxoc54930et2p2rd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fkc0bjsnhibfxoc54930et2p2rd FOREIGN KEY (partida_ida_id) REFERENCES public.partidas(id);


--
-- Name: suspensoes fkdtsji0k6v7730yyy9x3tef9i9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suspensoes
    ADD CONSTRAINT fkdtsji0k6v7730yyy9x3tef9i9 FOREIGN KEY (jogador_id) REFERENCES public.jogadores(id);


--
-- Name: partidas fkdwjii304ggmk4ktfl8oh2e7rq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT fkdwjii304ggmk4ktfl8oh2e7rq FOREIGN KEY (fase_eliminatoria_id) REFERENCES public.fases_eliminatorias(id);


--
-- Name: confrontos_eliminatorios fkeisko2aofhc8yuteebt1knarb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fkeisko2aofhc8yuteebt1knarb FOREIGN KEY (partida_volta_id) REFERENCES public.partidas(id);


--
-- Name: confrontos_eliminatorios fkgmc7gy4i6wqhpap1q3lcwnqhe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fkgmc7gy4i6wqhpap1q3lcwnqhe FOREIGN KEY (time_classificado_id) REFERENCES public.times(id);


--
-- Name: eventos_partida fkguvwalm0cc4yu7jvy7w1efy73; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_partida
    ADD CONSTRAINT fkguvwalm0cc4yu7jvy7w1efy73 FOREIGN KEY (jogador_secundario_id) REFERENCES public.jogadores(id);


--
-- Name: escalacao_partida fkhw2womnp2ytckrgxgcmcainup; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escalacao_partida
    ADD CONSTRAINT fkhw2womnp2ytckrgxgcmcainup FOREIGN KEY (partida_id) REFERENCES public.partidas(id);


--
-- Name: jogadores fkhxsr8cown495046kok6v10is; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jogadores
    ADD CONSTRAINT fkhxsr8cown495046kok6v10is FOREIGN KEY (time_id) REFERENCES public.times(id);


--
-- Name: campeonato_times fkljk9uxd555il3y3sxh1xndfoe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campeonato_times
    ADD CONSTRAINT fkljk9uxd555il3y3sxh1xndfoe FOREIGN KEY (campeonato_id) REFERENCES public.campeonatos(id);


--
-- Name: escalacao_partida fknhdi12yixa0ynsafvpapmkhrp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escalacao_partida
    ADD CONSTRAINT fknhdi12yixa0ynsafvpapmkhrp FOREIGN KEY (jogador_id) REFERENCES public.jogadores(id);


--
-- Name: estatisticas_jogador fko5457s5lmli1dwfe4uohks12v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estatisticas_jogador
    ADD CONSTRAINT fko5457s5lmli1dwfe4uohks12v FOREIGN KEY (jogador_id) REFERENCES public.jogadores(id);


--
-- Name: campeonato_times fkompdnlc2fyjiujv0yr2wo1gvh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campeonato_times
    ADD CONSTRAINT fkompdnlc2fyjiujv0yr2wo1gvh FOREIGN KEY (time_id) REFERENCES public.times(id);


--
-- Name: estatisticas_jogador_campeonato fkovosqelveqpw6t6n358dbpq7y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estatisticas_jogador_campeonato
    ADD CONSTRAINT fkovosqelveqpw6t6n358dbpq7y FOREIGN KEY (jogador_id) REFERENCES public.jogadores(id);


--
-- Name: grupos fkp2b1e5roc2reqtdaihhe0pw6s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos
    ADD CONSTRAINT fkp2b1e5roc2reqtdaihhe0pw6s FOREIGN KEY (campeonato_id) REFERENCES public.campeonatos(id);


--
-- Name: grupo_times fkqhj7scexf6335c2bxug95ixh7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupo_times
    ADD CONSTRAINT fkqhj7scexf6335c2bxug95ixh7 FOREIGN KEY (grupo_id) REFERENCES public.grupos(id);


--
-- Name: eventos_partida fkqyd97ou5ne6rtfv4ecii99umy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_partida
    ADD CONSTRAINT fkqyd97ou5ne6rtfv4ecii99umy FOREIGN KEY (partida_id) REFERENCES public.partidas(id);


--
-- Name: partidas fkr0y6qpiuxfir2ld48mrpvrw7x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partidas
    ADD CONSTRAINT fkr0y6qpiuxfir2ld48mrpvrw7x FOREIGN KEY (campeonato_id) REFERENCES public.campeonatos(id);


--
-- Name: grupo_times fksri9223x40fk9in88n9oxsow8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupo_times
    ADD CONSTRAINT fksri9223x40fk9in88n9oxsow8 FOREIGN KEY (time_id) REFERENCES public.times(id);


--
-- Name: confrontos_eliminatorios fktli36q3oy0aqb7x2v3i3qd8qo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confrontos_eliminatorios
    ADD CONSTRAINT fktli36q3oy0aqb7x2v3i3qd8qo FOREIGN KEY (proximo_confronto_id) REFERENCES public.confrontos_eliminatorios(id);


--
-- PostgreSQL database dump complete
--

\unrestrict AUCGz7AfKK5sqfPAz5VCb3hqq23GnDfx6JgCQaQFmoFNPaNqQ1VgDGQlbcDSOx2

